version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  community-db:
    image: postgres:15
    environment:
      POSTGRES_DB: community_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  profanity-db:
    image: postgres:15
    environment:
      POSTGRES_DB: profanity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./init-profanity-db.sql:/docker-entrypoint-initdb.d/init.sql
